import type { Metadata } from "next";
import "./globals.css";


import { LevelsProvider } from "@/components/providers/LevelsProvider";
import AppShell from "@/components/layout/AppShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LevelsProvider>
      <LayoutWithNavbar>{children}</LayoutWithNavbar>
    </LevelsProvider>
  );
}


function LayoutWithNavbar({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}

